In [2]:
#step1:we have to import the dataset to the colab notebook
import pandas as pd#pd is an instance of padnas
df=pd.read_csv('data.csv')#df is a variable,read_csv is a defined function from pandas package library and the Data.csv is a dataset which instance to the variable df)

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df#print variable to print data in csv

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
#step-2:grouping the input and output columns
X=df.iloc[:,:3]

In [6]:
X #separate the input columns in the data csv

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [7]:
Y=df.iloc[:,3:5]

In [8]:
Y

Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

In [9]:
X=X.values

In [10]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [11]:
Y=Y.values

In [12]:
Y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [13]:
#step-3:Handling missing data or values
#Senario-1:missing values in numerical column
#caluclate the mean or average of the column
#Senario-2:missing values in non numerical values
#sol-fill the column with high repeated value
#Senario-3:having missing in huge dataset(eg:20000 records in that 2 rows)
#sol:remove those empty values from the dataset
import numpy as np
from sklearn.impute import SimpleImputer
#sklearn:it is a python libaray widely used for machine learning and modelling
#impute:it is part of the sklearn
#simpleImputer:it is class which was import from sklearn.impute
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])



In [14]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [15]:
#Step4:handling the catagorial data(instead of number there is text formate is called catagorial data)converting catagorial data into numert from sklearn.preprocessing import OneHotEncoderFfrom sklearn.preprocessing import OneHotEncoder
from  sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer#columntransformer is the class import from sklearn.compose
#it is used to apply changes or transformers to column
#it is class which is used to apply the changes of numerical to text
#Alexa-0,0,1
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#encoder is a method which convert text to numeric
X=ct.fit_transform(X)

In [16]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [19]:
#Step5:split the data into training and text in data
from sklearn.model_selection import train_test_split#it is class which is import from sklearn.model_selection
#it is used spliting the data into training and testing
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [20]:
X_train

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [21]:
X_test

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [22]:
Y_train

array([0, 0, 1, 0, 1, 0, 1, 1])

In [23]:
Y_test

array([1, 0])

In [25]:
#step6:features scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train[:,3:]=sc.fit_transform(X_train[:,3:])
X_test[:,3:]=sc.transform(X_test[:,3:])

In [26]:
X_train

array([[0.0, 0.0, 1.0, 0.14568005958011257, -1.023843130833262],
       [0.0, 1.0, 0.0, -1.2284960248173666, -0.8210461420574852],
       [0.0, 0.0, 1.0, -1.6981511422696696, -1.4294371083848156],
       [1.0, 0.0, 0.0, 0.9632278566267138, 1.0041267569245058],
       [1.0, 0.0, 0.0, 1.5894346798964512, 1.7139162176397245],
       [0.0, 0.0, 1.0, 0.023917621722107978, -0.11125668134226646],
       [0.0, 1.0, 0.0, 0.33702103335697664, 0.17040580306853495],
       [1.0, 0.0, 0.0, -0.13263408409532634, 0.4971342849850639]],
      dtype=object)

In [27]:
X_test


array([[1.0, 0.0, 0.0, 35.0, 58000.00000000001],
       [0.0, 1.0, 0.0, 50.0, 83000.00000000001]], dtype=object)

In [28]:
#step-:7
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression()

In [30]:
Y_pred=classifier.predict(X_test)

In [31]:
Y_pred

array([1, 1])